version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - |
      python -m pip install hatch
      if [ "$READTHEDOCS_VERSION_TYPE" != "tag" ]; then
        hatch env run --env docs -- towncrier build --version Unreleased --yes
      fi
      hatch env run --env docs build
      hatch env run --env docs readthedocs
