version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" != "tag" ];
        then
          towncrier build --version Unreleased --yes;
        fi
  commands:
    - mamba install -c conda-forge -c nodefaults hatch
    - hatch env run --env docs build
    - hatch env run --env docs readthedocs

