# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: os=${{ matrix.os }}, py=${{ matrix.python-version }}, np=${{ matrix.numpy-version }}, deps=${{ matrix.dependency-set }}

    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        numpy-version: ['1.25', '2.1']
        dependency-set: ["minimal", "optional"]
        os: ["ubuntu-latest"]
        include:
          - python-version: '3.11'
            numpy-version: '1.25'
            dependency-set: 'optional'
            os: 'macos-latest'
          - python-version: '3.13'
            numpy-version: '2.1'
            dependency-set: 'optional'
            os: 'macos-latest'
          - python-version: '3.11'
            numpy-version: '1.25'
            dependency-set: 'optional'
            os: 'windows-latest'
          - python-version: '3.13'
            numpy-version: '2.1'
            dependency-set: 'optional'
            os: 'windows-latest'
          - python-version: '3.11'
            dependency-set: 'min_deps'
            os: 'ubuntu-latest'
          - python-version: '3.13'
            dependency-set: 'upstream'
            os: 'ubuntu-latest'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # grab all branches and tags
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Set environment name
      id : hatch-env-name
      run : |
        if [[ ${{ matrix.dependency-set }} = 'upstream' ]]; then
          HATCH_ENV="upstream"
        elif [[ ${{ matrix.dependency-set }} = 'min_deps' ]]; then
          HATCH_ENV="min_deps"
        else
          HATCH_ENV="test.py${{ matrix.python-version }}-${{ matrix.numpy-version }}-${{ matrix.dependency-set }}"
        fi
        echo "HATCH_ENV=${HATCH_ENV}" >> "$GITHUB_OUTPUT"

    - name: Set Up Hatch Env
      env:
          HATCH_ENV: ${{ steps.hatch-env-name.outputs.HATCH_ENV }}
      run: |
        hatch env create ${HATCH_ENV}
        hatch env run -e ${HATCH_ENV} list-env
    - name: Run Tests
      env:
          HATCH_ENV: ${{ steps.hatch-env-name.outputs.HATCH_ENV }}
      run: |
        hatch env run --env ${HATCH_ENV} run-coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      if: ${{ !env.ACT }} # Skip during local testing
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true # optional (default = false)

  doctests:
    name: doctests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for hatch version discovery, which is needed for numcodecs.zarr3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Set Up Hatch Env
      run: |
        hatch env create doctest
        hatch env run -e doctest list-env
    - name: Run Tests
      run: |
        hatch env run --env doctest run

  test-complete:
    name: Test complete
    needs:
      [
        test,
        test-upstream-and-min-deps,
        doctests
      ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check failure
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
        run: exit 1
      - name: Success
        run: echo Success!
